[package]
name = "ikaria"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
bevy = { workspace = true }
ikaria-shared = { workspace = true }
