[package]
name = "ikariadb"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
ikaria-shared = { workspace = true }

spacetimedb = { workspace = true }
thiserror = { workspace = true }
