[package]
name = "ikaria-server"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
anyhow = { workspace = true }
spacetimedb = { workspace = true }
ikaria-shared = { workspace = true }
