[package]
name = "world-draconis-ikariadb"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
ikariadb-core = { workspace = true }

spacetimedb = { workspace = true }
